version: '3.8'
services:
  nats:
    image: nats:2.10
    container_name: payslip-nats
    ports:
      - "4222:4222"
      - "8222:8222" # monitoring
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "51214:5432"
    environment:
      POSTGRES_USER: devdb
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes:
    postgres_data: 
